file_path: ../webscrap-website/amazonreviews/data
freq: 15
output_dir: ../webscrap-website/amazonreviews/output/raw
log_output: ../webscrap-website/amazonreviews/output/logs/
final_output: ../webscrap-website/amazonreviews/output/consolidated
tracker_output: ../webscrap-website/amazonreviews/output/tracker/
num_retry: 2